app = 'maybe'
primary_region = 'sjc'

[build]
  image = 'ghcr.io/maybe-finance/maybe:latest'

[env]
  GOOD_JOB_EXECUTION_MODE = 'async'
  RAILS_ASSUME_SSL = 'false'
  RAILS_FORCE_SSL = 'false'
  SELF_HOSTED = 'true'
  # SET WITH FLY SECRETS:
  # SECRET_KEY_BASE = ''
  # DB_HOST = ''
  # POSTGRES_DB = ''
  # POSTGRES_USER = ''
  # POSTGRES_PASSWORD = ''

[[mounts]]
  source = 'maybe_storage'
  destination = '/rails/storage'
  initial_size = '1g'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpus = 1
