app = 'surrealdb'
primary_region = 'sjc'

[experimental]
  cmd = ["start", "--bind", "0.0.0.0:8000", "file://data/srdb.db"]

[build]
  image = 'surrealdb/surrealdb:latest'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1g'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpus = 1
