# app = 'actual'
primary_region = 'sjc'

[experimental]
  cmd = ['node', '--max-old-space-size=180', 'app.js']

[build]
  image = 'actualbudget/actual-server:latest'

[env]
  PORT = '5006'
  TINI_SUBREAPER = '1'

[[mounts]]
  source = 'actual_data'
  destination = '/data'
  initial_size = '1g'

[http_service]
  internal_port = 5006
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
