app = 'minecraft-server-morning-sun-1582'
primary_region = 'sjc'

[build]
  image = 'itzg/minecraft-server'

[env]
  MEMORY = '1G'
  SERVER_PORT = '25565'
  SERVER_HOST = 'localhost'
  TZ = 'US/Pacific'
  EULA = 'TRUE'
  VERSION = 'LATEST' # Configure the Minecraft version
  ENABLE_ROLLING_LOGS = 'true'
  ENABLE_RCON = 'false'
  RCON_PORT = '28016'
  # RCON_PASSWORD = 'testing' # SET WITH `fly secrets set RCON_PASSWORD=testing`
  SERVER_NAME = 'FlyServer'
  MOTD = 'Welcome to Minecraft on Fly.io!'
  DIFFICULTY = 'easy'
  MODE = 'survival'
  PVP = 'true'
  LOG_IPS = 'true'
  # SEED = '1785852800490497919'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '2g'

[[services]]
  protocol = 'tcp'
  internal_port = 25565
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  [[services.ports]]
    handlers = []
    port = 25565

[[vm]]
  memory = '1gb'
  cpus = 1
