# app = 'dragonfly-db'
primary_region = 'sjc'

[build]
  image = 'docker.dragonflydb.io/dragonflydb/dragonfly'

[env]
  ADMIN_CONSOLE = 'false'
  HOST = 'fly-local-6pn'
  PORT = '6379'

[processes]
  app = 'dragonfly --logtostderr --bind fly-local-6pn --port 6379 --primary_port_http_enabled'

[[mounts]]
  source = 'data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 6379
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
