app = 'meilisearch'
primary_region = 'sjc'

[build]
  image = 'getmeili/meilisearch:latest'

[env]
  MEILI_ENV = 'production'
  # SET WITH FLY SECRETS:
  # MEILI_MASTER_KEY = ''

[[mounts]]
  source = 'meili_data'
  destination = '/meili_data'
  initial_size = '1g'

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpus = 1